### ISSUE TITLE
SPM Target Support

### ISSUE THREAD

**Issue by agarrharr** [wojciech-kulik/xcodebuild.nvim#127] opened 2024-04-02 21:42 UTC
I'm not sure what the difference is, but I have 2 different projects that are set up in pretty much the same way, with an spm package that has many modules. One of them correctly shows all of the schemes when I run `:XcodebuildSetup` and the other one does not. I can provide more information if needed.

This one is correct:
<img width="754" alt="Screenshot 2024-04-02 at 3 40 10 PM" src="https://github.com/wojciech-kulik/xcodebuild.nvim/assets/3266363/5992f13b-aaed-4996-aabb-67c10ccd41e5">

And this one only shows 2 schemes:
<img width="660" alt="Screenshot 2024-04-02 at 3 41 02 PM" src="https://github.com/wojciech-kulik/xcodebuild.nvim/assets/3266363/5c1010cc-4e26-4105-8fb7-ee2dc7944fa1">

**Comment by agarrharr** [comment] 2024-04-02 23:23
Interesting. Well, for the project that works, I don't have any `.xcscheme` files in my `.xcodeproj`...

<img width="925" alt="Screenshot 2024-04-02 at 5 22 54 PM" src="https://github.com/wojciech-kulik/xcodebuild.nvim/assets/3266363/53c38f3e-e926-4085-b499-327b286a5c03">

**Comment by agarrharr** [comment] 2024-04-02 23:26
And for the one that doesn't work, it DOES have an `.xcscheme`... I'm not sure how to click around to make it update...
 
<img width="725" alt="Screenshot 2024-04-02 at 5 25 33 PM" src="https://github.com/wojciech-kulik/xcodebuild.nvim/assets/3266363/19d3a3a5-40bc-4700-9c08-02bfa3525bcd">

**Comment by agarrharr** [comment] 2024-04-02 23:52
I tried deleting the `Countable.xcodeproj/xcuserdata` folder and if can now find all of the schemes from my spm module, but of course it can't find the schemes app targets or widget extension (and neither can Xcode obviously).

<img width="1059" alt="Screenshot 2024-04-02 at 5 50 23 PM" src="https://github.com/wojciech-kulik/xcodebuild.nvim/assets/3266363/b3c4f356-59d5-41f0-98a2-25b7668c78b0">

**Comment by notlus** [comment] 2024-04-02 23:52
I ran into this as well. My SwiftPM schemes were in the `.swiftpm/xcode/xcschemes` folder for the package, with nothing in the `xcodeproj` folder. Moving the schemes into the `xcodeproj` folder and updating the project seems to work. Ideally this should not be necessary, given that Xcode seems able to find these schemes.

The other schemes were visible prior to [PR 96](https://github.com/wojciech-kulik/xcodebuild.nvim/pull/96).

**Comment by wojciech-kulik** [comment] 2024-04-02 23:53
Ahhh, so there could be schemes also in `.swiftpm/xcode/xcschemes`. I didn't know about this path.

**Comment by wojciech-kulik** [comment] 2024-04-03 00:00
I will need to investigate it, for now I'm reverting the improvement to find schemes based on generated files. Let me know if it resolves your issue.

**Comment by agarrharr** [comment] 2024-04-03 01:37
Thanks, that does fix the issue for me. They all show up now!

**Comment by agarrharr** [comment] 2024-04-03 01:39
If you need a project to test with, this is the one that had the problem: https://github.com/agarrharr/Countable

**Comment by notlus** [comment] 2024-04-03 15:18
For my use-case, this change was a huge benefit. I have a large macOS project with multiple SPM packages. Working in the project involves changing schemes often, depending on what is being worked on. Building the SPM packages via the parent target is very time consuming, and it does not allow me to use the test explorer to run tests for a specific package. This increases the build/test time significantly.

**Comment by agarrharr** [comment] 2024-04-03 15:30
Ah, great questions. I don't really need to select them, I was just surprised that they were missing from this list. Technically, it would make it build faster if I was working on one small module at a time.

But if I'm working on a SwiftUI view, I have Xcode in the background and I have an AppleScript that automatically switches to that scheme in Xcode when I save a file so that I can see the SwiftUI preview.

Now that I think about it though, I would need to select one of them to run their tests, right?

**Comment by wojciech-kulik** [comment] 2024-04-03 15:50
Currently, tests are supported only via test plans, so if you configure a test plan in your main app that runs tests from specific module you should be able to do that without selecting SPM target.

@notlus for now you can switch to specific commit if this solution worked for you. But keep in mind that build configuration detection doesn't work there, so if you use a different build configuration then "Debug" it won't work correctly. 

I need to figure out if and how to support SPM packages, basically it's a different flow than for apps. I guess I would have to support two modes xcodeproj/xcworkspace and SPM module with a different set of commands and behaviors.

**Comment by agarrharr** [comment] 2024-04-03 15:58
Yeah, so I'm running an app that includes a single module from an spm package (called AppFeature) under "Frameworks, Libraries, and Embedded Content". In that package, AppFeature has a dependency on other modules and an external library. I think you already understand, but I wanted to be clear and a picture is worth a thousand words.

<img width="1839" alt="xcode" src="https://github.com/wojciech-kulik/xcodebuild.nvim/assets/3266363/4480cdf4-9cd1-45c8-b2eb-806bcb5d78ab">

**Comment by wojciech-kulik** [comment] 2024-04-04 11:14
> I also have this issue with sub-projects. The main Xcode project has some dependencies as child Xcode projects and like the SPM schemes, their schemes are not visible. In Xcode, I can select schemes across the projects.

Ok, this is a bug caused by looking for schemes inside a single `xcodeproj`. I need to verify if it's just that, if the plugin in general is able to work with other xcodeprojs included. But I think it should work if the scheme is correctly detected.

> The main project has multiple peer targets (there is no main app), none of which currently have test plans. I will see whether I can add test plans for them, but it seems like each test plan would need to be configured to run the SPM tests.

If you wrap your main module inside an app project. You can then create a test plan that will include tests from each SPM package, a single test plan. I was using a similar approach in a project where I was working on a modularized application using SPM. We had just a "demo" project to include this package, run tests, and test in general the functionality.

**Comment by wojciech-kulik** [comment] 2024-11-03 18:37
@agarrharr @notlus I added support for SPM packages. I don't know if you are still using the plugin, but I would appreciate if someone could test it and check if it works as expected :).

**Comment by notlus** [comment] 2024-11-04 17:22
@wojciech-kulik On a simple project that I have it is working fine. However on the main project that I work on, I am able to discover the Swift packages, but unable to build them. I get the error "The directory /Users/me/ProjectRoot/ does not contain an Xcode project, workspace or package.". I believe it is because the Xcode project file is not in the root of the project. E.g.

ProjectRoot/
├── MainProject/
│   └── main.xcodeproj
├── Packages/
│   └── SomePackage/
├── Tools/
└── etc/

I use the plugin at the root of the project, because there are many other projects that are peers to the main project and I want to be able to edit and build those projects.

**Comment by wojciech-kulik** [comment] 2024-11-04 19:04
Could you download the latest version from the main branch and try again? I'm not sure which version you checked but there were some issues that I fixed already.

You should be able to pick `Package.swift` & build even if your working directory differs.

However, to switch between packages you will need to run configuration wizard every time. So I think the most efficient way is to navigate to `Package.swfit` and create `xcodebuild.nvim` project there. You can then even have multiple terminal sessions with different projects to switch between them without any extra effort.

**Comment by notlus** [comment] 2024-11-04 19:45
@wojciech-kulik With the version from main, it is working correctly for me.

Regarding switching packages, I think I will do as you suggested.

Would it be possible to allow for specifying configurations that you could switch between without needing to run the wizard?

**Comment by wojciech-kulik** [comment] 2024-11-04 19:55
Great to hear! 🎊 I'm closing this ticket then.

Could you create a new feature request to quickly switch between configurations?

If you use my suggested approach, you won't have to run the wizard every time because the config directory is created in your working directory. The only thing you need to do is navigate to your `Package.swift` and run Neovim, each directory with `Package.swift` will have it's own config.
If you use tmux or any other session multiplexer you can very quickly switch between projects.

**Closed by wojciech-kulik** 2024-11-04 19:55 UTC
Labels: feature request

**Comment by notlus** [comment] 2024-11-04 20:01
The one thing missing from using separate sessions, is that often I want to search or use the LSP to find uses of the package's API. With separate sessions, nvim instances don't have visibility into this information.

I will try using the separate sessions, and if I find it not working as well as switching configurations, I will create a feature request.

**Comment by wojciech-kulik** [comment] 2024-11-04 20:15
You're right, but to make LSP work across all packages I think you need `xcodeproj`, correct? 
I'm not sure if sourcekit-lsp itself is able to navigate between local packages.

**Comment by notlus** [comment] 2024-11-04 20:26
Yes, that is correct.

Prior to PR #96, the schemes for Swift packages used by the configured Xcode project were visible and could be selected within the currently configured Xcode project. Those schemed are located in .swiftpm/xcode/xcshareddata/xcschemes.

To work around this, I copied the xcscheme files from the package into the Xcode project's xcshareddata/xcschemes folder. After doing this, the schemes were selectable using the configured Xcode project. This allows for the LSP to find things across the package and the Xcode project.

**Comment by wojciech-kulik** [comment] 2024-11-04 20:39
> To work around this, I copied the xcscheme files from the package into the Xcode project's xcshareddata/xcschemes folder. After doing this, the schemes were selectable using the configured Xcode project. This allows for the LSP to find things across the package and the Xcode project.

Interesting, so without schemes, it doesn't work? Shouldn't it work out-of-the-box if you have an Xcode project that adds all packages as dependencies?

The PR that you mentioned shouldn't affect how the LSP works, because the plugin doesn't provide any data to the LSP. Maybe you are thinking about the scheme provided to `xcode-build-server`? The plugin calls this tool to update `buildServer.json` (which also contains the selected scheme)

**Comment by notlus** [comment] 2024-11-04 22:16
Xcode recognizes the schemes located at .swiftpm/xcode/xcshareddata/xcschemes and they can be selected from within Xcode. Via the plugin, those same schemes are not available, unless they are copied inside of the Xcode project bundle.

Regarding the PR, I think it is related to the fact that the schemes are not visible to `xcode-build-server`.
